### ISSUE TITLE
use block centering method

### ISSUE THREAD

**Issue by JGJP** [pineappledreams/pineappledreams.github.io#1]
https://github.com/pineappledreams/pineappledreams.github.io/blob/fefaad7125207e89010b218dd3b2523ab6deadcc/index.html#L59

for elements like this you should be using this method to center:

```
.titlebox {
    margin: 0 auto /* centers any element that is display: block (all divs by default) */
    width: 40em /* change this to widen or narrow the box */
    max-width: 100% /* will always fit on mobile */
}
```

**Comment by pineappledreams** [comment]
Thank you very much for your issue report, I implemented the fixes and it looks nicer now. If only I would find a way for the <p> element inside the box to fill out the entire under box would be great.

**Comment by JGJP** [comment]
if you want to center the contents do something like this:

```
.titlebox {
    display: flex
    justify-content: center
    align-items: center
    flex-direction: column
}
```

Also be aware that when you only have one child you can use this method to center vertically, it's more compatible with older browsers (that really shouldn't be a concern for this project, just know about it) :

```
.titlebox .child {
    position: relative;
    top: 50%;
    transform: translateY(-50%);
}
```
